name: helm

on:
  pull_request:

jobs:
  lint:
    runs-on: docker
    container:
      image: alpine/helm:4.3.0
    steps:
      - name: Install git
        run: apk add --no-cache git
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 #v4.4.0
      - name: Lint Helm Chart
        run: helm lint ./charts/netbird-operator