// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/netbirdio/kubernetes-operator/api/v1alpha1"
	apiv1alpha1 "github.com/netbirdio/kubernetes-operator/pkg/applyconfigurations/api/v1alpha1"
	internal "github.com/netbirdio/kubernetes-operator/pkg/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=netbird.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AccessRestrictions"):
		return &apiv1alpha1.AccessRestrictionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterProxy"):
		return &apiv1alpha1.ClusterProxyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterProxySpec"):
		return &apiv1alpha1.ClusterProxySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterProxyStatus"):
		return &apiv1alpha1.ClusterProxyStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerOverride"):
		return &apiv1alpha1.ContainerOverrideApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CrossNamespaceReference"):
		return &apiv1alpha1.CrossNamespaceReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSRecord"):
		return &apiv1alpha1.DNSRecordApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSRecordSpec"):
		return &apiv1alpha1.DNSRecordSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSRecordStatus"):
		return &apiv1alpha1.DNSRecordStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSZone"):
		return &apiv1alpha1.DNSZoneApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSZoneSpec"):
		return &apiv1alpha1.DNSZoneSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSZoneStatus"):
		return &apiv1alpha1.DNSZoneStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Group"):
		return &apiv1alpha1.GroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupReference"):
		return &apiv1alpha1.GroupReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupSpec"):
		return &apiv1alpha1.GroupSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GroupStatus"):
		return &apiv1alpha1.GroupStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Network"):
		return &apiv1alpha1.NetworkApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResource"):
		return &apiv1alpha1.NetworkResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceSpec"):
		return &apiv1alpha1.NetworkResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceStatus"):
		return &apiv1alpha1.NetworkResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkSpec"):
		return &apiv1alpha1.NetworkSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkStatus"):
		return &apiv1alpha1.NetworkStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ReverseProxyService"):
		return &apiv1alpha1.ReverseProxyServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ReverseProxyServiceSpec"):
		return &apiv1alpha1.ReverseProxyServiceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ReverseProxyServiceStatus"):
		return &apiv1alpha1.ReverseProxyServiceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RouteReference"):
		return &apiv1alpha1.RouteReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKey"):
		return &apiv1alpha1.SetupKeyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeySpec"):
		return &apiv1alpha1.SetupKeySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SetupKeyStatus"):
		return &apiv1alpha1.SetupKeyStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfile"):
		return &apiv1alpha1.SidecarProfileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfileSpec"):
		return &apiv1alpha1.SidecarProfileSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SidecarProfileStatus"):
		return &apiv1alpha1.SidecarProfileStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
