// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DNSRecordSpecApplyConfiguration represents a declarative configuration of the DNSRecordSpec type for use
// with apply.
//
// DNSRecordSpec defines the desired state of DNSRecord. It mirrors the NetBird
// DNS-record API (POST /api/dns/zones/{zone}/records) 1:1: a single record in a
// zone. The controller adopts an existing record matching name+type+content
// rather than recreating it (NetBird rejects duplicate records).
type DNSRecordSpecApplyConfiguration struct {
	// ZoneRef references the DNSZone this record is created in. The zone must be
	// Ready; its status.zoneID identifies the NetBird zone.
	ZoneRef *CrossNamespaceReferenceApplyConfiguration `json:"zoneRef,omitempty"`
	// Name is the record name (a fully qualified name under the zone).
	Name *string `json:"name,omitempty"`
	// Type is the record type.
	Type *string `json:"type,omitempty"`
	// Content is the record content (e.g. the IP for an A/AAAA record).
	Content *string `json:"content,omitempty"`
	// TTL is the record TTL in seconds. Defaults to 300.
	TTL *int `json:"ttl,omitempty"`
}

// DNSRecordSpecApplyConfiguration constructs a declarative configuration of the DNSRecordSpec type for use with
// apply.
func DNSRecordSpec() *DNSRecordSpecApplyConfiguration {
	return &DNSRecordSpecApplyConfiguration{}
}

// WithZoneRef sets the ZoneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneRef field is set to the value of the last call.
func (b *DNSRecordSpecApplyConfiguration) WithZoneRef(value *CrossNamespaceReferenceApplyConfiguration) *DNSRecordSpecApplyConfiguration {
	b.ZoneRef = value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSRecordSpecApplyConfiguration) WithName(value string) *DNSRecordSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DNSRecordSpecApplyConfiguration) WithType(value string) *DNSRecordSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithContent sets the Content field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Content field is set to the value of the last call.
func (b *DNSRecordSpecApplyConfiguration) WithContent(value string) *DNSRecordSpecApplyConfiguration {
	b.Content = &value
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *DNSRecordSpecApplyConfiguration) WithTTL(value int) *DNSRecordSpecApplyConfiguration {
	b.TTL = &value
	return b
}
