// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DNSZoneStatusApplyConfiguration represents a declarative configuration of the DNSZoneStatus type for use
// with apply.
//
// DNSZoneStatus defines the observed state of DNSZone.
type DNSZoneStatusApplyConfiguration struct {
	// ObservedGeneration is the last reconciled generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the DNSZone.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ZoneID is the id of the managed NetBird zone.
	ZoneID *string `json:"zoneID,omitempty"`
}

// DNSZoneStatusApplyConfiguration constructs a declarative configuration of the DNSZoneStatus type for use with
// apply.
func DNSZoneStatus() *DNSZoneStatusApplyConfiguration {
	return &DNSZoneStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DNSZoneStatusApplyConfiguration) WithObservedGeneration(value int64) *DNSZoneStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DNSZoneStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DNSZoneStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithZoneID sets the ZoneID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneID field is set to the value of the last call.
func (b *DNSZoneStatusApplyConfiguration) WithZoneID(value string) *DNSZoneStatusApplyConfiguration {
	b.ZoneID = &value
	return b
}
