// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DNSZoneSpecApplyConfiguration represents a declarative configuration of the DNSZoneSpec type for use
// with apply.
//
// DNSZoneSpec defines the desired state of DNSZone. It mirrors the NetBird
// DNS-zones API (POST /api/dns/zones) 1:1. The controller adopts an existing
// zone with the same domain rather than failing, so a zone provisioned out of
// band is taken over.
type DNSZoneSpecApplyConfiguration struct {
	// Name of the managed zone.
	Name *string `json:"name,omitempty"`
	// Domain is the zone apex, e.g. "kube.example.com".
	Domain *string `json:"domain,omitempty"`
	// DistributionGroups are the NetBird groups whose peers receive the zone, so
	// they can resolve records in it. The reverse-proxy cluster that fronts a
	// service must be in one of these groups for hostname upstreams to resolve.
	DistributionGroups []GroupReferenceApplyConfiguration `json:"distributionGroups,omitempty"`
	// EnableSearchDomain adds the zone as a search domain on distributed peers.
	EnableSearchDomain *bool `json:"enableSearchDomain,omitempty"`
	// Enabled controls whether the zone is active. Defaults to true.
	Enabled *bool `json:"enabled,omitempty"`
}

// DNSZoneSpecApplyConfiguration constructs a declarative configuration of the DNSZoneSpec type for use with
// apply.
func DNSZoneSpec() *DNSZoneSpecApplyConfiguration {
	return &DNSZoneSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSZoneSpecApplyConfiguration) WithName(value string) *DNSZoneSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *DNSZoneSpecApplyConfiguration) WithDomain(value string) *DNSZoneSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithDistributionGroups adds the given value to the DistributionGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DistributionGroups field.
func (b *DNSZoneSpecApplyConfiguration) WithDistributionGroups(values ...*GroupReferenceApplyConfiguration) *DNSZoneSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDistributionGroups")
		}
		b.DistributionGroups = append(b.DistributionGroups, *values[i])
	}
	return b
}

// WithEnableSearchDomain sets the EnableSearchDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableSearchDomain field is set to the value of the last call.
func (b *DNSZoneSpecApplyConfiguration) WithEnableSearchDomain(value bool) *DNSZoneSpecApplyConfiguration {
	b.EnableSearchDomain = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DNSZoneSpecApplyConfiguration) WithEnabled(value bool) *DNSZoneSpecApplyConfiguration {
	b.Enabled = &value
	return b
}
