// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkResourceSpecApplyConfiguration represents a declarative configuration of the NetworkResourceSpec type for use
// with apply.
//
// NetworkResourceSpec defines the desired state of NetworkResource. It mirrors
// the NetBird network-resource API (POST /api/networks/{network}/resources) 1:1:
// a single address routed into a network, with groups. DNS is handled
// separately by DNSRecord; IP-family fan-out is done by the translation layer
// (one NetworkResource per address family).
type NetworkResourceSpecApplyConfiguration struct {
	// NetworkRef references the Network this resource is created in. The Network
	// must be Ready; its status.networkID identifies the NetBird network.
	NetworkRef *CrossNamespaceReferenceApplyConfiguration `json:"networkRef,omitempty"`
	// Name of the resource.
	Name *string `json:"name,omitempty"`
	// Address is the single resource address — an IP, CIDR, or domain. NetBird
	// derives the resource type from it.
	Address *string `json:"address,omitempty"`
	// Description of the resource.
	Description *string `json:"description,omitempty"`
	// Groups are the NetBird groups this resource is a part of, referenced by
	// name, id, or local Group reference.
	Groups []GroupReferenceApplyConfiguration `json:"groups,omitempty"`
	// Enabled controls whether the resource is active. Defaults to true.
	Enabled *bool `json:"enabled,omitempty"`
}

// NetworkResourceSpecApplyConfiguration constructs a declarative configuration of the NetworkResourceSpec type for use with
// apply.
func NetworkResourceSpec() *NetworkResourceSpecApplyConfiguration {
	return &NetworkResourceSpecApplyConfiguration{}
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithNetworkRef(value *CrossNamespaceReferenceApplyConfiguration) *NetworkResourceSpecApplyConfiguration {
	b.NetworkRef = value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithName(value string) *NetworkResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithAddress(value string) *NetworkResourceSpecApplyConfiguration {
	b.Address = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithDescription(value string) *NetworkResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *NetworkResourceSpecApplyConfiguration) WithGroups(values ...*GroupReferenceApplyConfiguration) *NetworkResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGroups")
		}
		b.Groups = append(b.Groups, *values[i])
	}
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithEnabled(value bool) *NetworkResourceSpecApplyConfiguration {
	b.Enabled = &value
	return b
}
