// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkSpecApplyConfiguration represents a declarative configuration of the NetworkSpec type for use
// with apply.
//
// NetworkSpec defines the desired state of Network. It mirrors the NetBird
// Networks API (POST /api/networks) 1:1.
type NetworkSpecApplyConfiguration struct {
	// Name of the NetBird network.
	Name *string `json:"name,omitempty"`
	// Description of the network.
	Description *string `json:"description,omitempty"`
}

// NetworkSpecApplyConfiguration constructs a declarative configuration of the NetworkSpec type for use with
// apply.
func NetworkSpec() *NetworkSpecApplyConfiguration {
	return &NetworkSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithName(value string) *NetworkSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithDescription(value string) *NetworkSpecApplyConfiguration {
	b.Description = &value
	return b
}
