// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkRouterPeersApplyConfiguration represents a declarative configuration of the NetworkRouterPeers type for use
// with apply.
//
// NetworkRouterPeers selects the routing peers. Exactly one field must be set.
type NetworkRouterPeersApplyConfiguration struct {
	// Group reuses an existing NetBird group as the routing peers (e.g. the group
	// the host-level netbird on the cluster nodes auto-joins). The operator
	// creates only the router and deploys nothing.
	Group *GroupReferenceApplyConfiguration `json:"group,omitempty"`
	// Deploy runs a hostNetwork DaemonSet of netbird-client as the routing peers;
	// the operator manages its Group, SetupKey and DaemonSet.
	Deploy *RouterDeployApplyConfiguration `json:"deploy,omitempty"`
}

// NetworkRouterPeersApplyConfiguration constructs a declarative configuration of the NetworkRouterPeers type for use with
// apply.
func NetworkRouterPeers() *NetworkRouterPeersApplyConfiguration {
	return &NetworkRouterPeersApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *NetworkRouterPeersApplyConfiguration) WithGroup(value *GroupReferenceApplyConfiguration) *NetworkRouterPeersApplyConfiguration {
	b.Group = value
	return b
}

// WithDeploy sets the Deploy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deploy field is set to the value of the last call.
func (b *NetworkRouterPeersApplyConfiguration) WithDeploy(value *RouterDeployApplyConfiguration) *NetworkRouterPeersApplyConfiguration {
	b.Deploy = value
	return b
}
