// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkRouterSpecApplyConfiguration represents a declarative configuration of the NetworkRouterSpec type for use
// with apply.
//
// NetworkRouterSpec mirrors the NetBird router API
// (POST /api/networks/{network}/routers) and adds the routing-peer source: an
// existing NetBird group, or a netbird-client DaemonSet the operator deploys.
type NetworkRouterSpecApplyConfiguration struct {
	// NetworkRef references the Network this router belongs to. The Network must
	// be Ready; its status.networkID identifies the NetBird network.
	NetworkRef *CrossNamespaceReferenceApplyConfiguration `json:"networkRef,omitempty"`
	// Peers selects the routing peers — exactly one of group or deploy.
	Peers *NetworkRouterPeersApplyConfiguration `json:"peers,omitempty"`
	// Masquerade makes the routing peers SNAT traffic to the routed resources.
	Masquerade *bool `json:"masquerade,omitempty"`
	// Metric is the route metric; the lowest number wins.
	Metric *int `json:"metric,omitempty"`
	// Enabled controls whether the router is active.
	Enabled *bool `json:"enabled,omitempty"`
}

// NetworkRouterSpecApplyConfiguration constructs a declarative configuration of the NetworkRouterSpec type for use with
// apply.
func NetworkRouterSpec() *NetworkRouterSpecApplyConfiguration {
	return &NetworkRouterSpecApplyConfiguration{}
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *NetworkRouterSpecApplyConfiguration) WithNetworkRef(value *CrossNamespaceReferenceApplyConfiguration) *NetworkRouterSpecApplyConfiguration {
	b.NetworkRef = value
	return b
}

// WithPeers sets the Peers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Peers field is set to the value of the last call.
func (b *NetworkRouterSpecApplyConfiguration) WithPeers(value *NetworkRouterPeersApplyConfiguration) *NetworkRouterSpecApplyConfiguration {
	b.Peers = value
	return b
}

// WithMasquerade sets the Masquerade field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Masquerade field is set to the value of the last call.
func (b *NetworkRouterSpecApplyConfiguration) WithMasquerade(value bool) *NetworkRouterSpecApplyConfiguration {
	b.Masquerade = &value
	return b
}

// WithMetric sets the Metric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metric field is set to the value of the last call.
func (b *NetworkRouterSpecApplyConfiguration) WithMetric(value int) *NetworkRouterSpecApplyConfiguration {
	b.Metric = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *NetworkRouterSpecApplyConfiguration) WithEnabled(value bool) *NetworkRouterSpecApplyConfiguration {
	b.Enabled = &value
	return b
}
