// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NetworkResourceEntryApplyConfiguration represents a declarative configuration of the NetworkResourceEntry type for use
// with apply.
//
// NetworkResourceEntry is a NetBird host resource created for one of a Service's
// ClusterIP families.
type NetworkResourceEntryApplyConfiguration struct {
	// Family is the IP family ("IPv4" or "IPv6").
	Family *string `json:"family,omitempty"`
	// Address is the ClusterIP the resource points at.
	Address *string `json:"address,omitempty"`
	// ResourceID is the NetBird resource id.
	ResourceID *string `json:"resourceID,omitempty"`
}

// NetworkResourceEntryApplyConfiguration constructs a declarative configuration of the NetworkResourceEntry type for use with
// apply.
func NetworkResourceEntry() *NetworkResourceEntryApplyConfiguration {
	return &NetworkResourceEntryApplyConfiguration{}
}

// WithFamily sets the Family field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Family field is set to the value of the last call.
func (b *NetworkResourceEntryApplyConfiguration) WithFamily(value string) *NetworkResourceEntryApplyConfiguration {
	b.Family = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *NetworkResourceEntryApplyConfiguration) WithAddress(value string) *NetworkResourceEntryApplyConfiguration {
	b.Address = &value
	return b
}

// WithResourceID sets the ResourceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceID field is set to the value of the last call.
func (b *NetworkResourceEntryApplyConfiguration) WithResourceID(value string) *NetworkResourceEntryApplyConfiguration {
	b.ResourceID = &value
	return b
}
