// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ReverseProxyClusterStatusApplyConfiguration represents a declarative configuration of the ReverseProxyClusterStatus type for use
// with apply.
//
// ReverseProxyClusterStatus defines the observed state of ReverseProxyCluster.
type ReverseProxyClusterStatusApplyConfiguration struct {
	// ObservedGeneration is the last reconciled generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the ReverseProxyCluster.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ClusterAddress echoes the registered cluster address once the proxy has
	// enrolled (resolvable via the Management API).
	ClusterAddress *string `json:"clusterAddress,omitempty"`
	// TokenID is the id of the minted proxy token (revoked when the cluster is
	// deleted).
	TokenID *string `json:"tokenID,omitempty"`
	// DomainID is the id of the registered NetBird custom domain (Domain ->
	// ClusterAddress), so service domains under it derive this cluster. Removed
	// when the cluster is deleted.
	DomainID *string `json:"domainID,omitempty"`
	// LoadBalancerIP is the proxy Service's assigned ingress IP — what the A
	// record points at.
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty"`
	// Online reports whether at least one proxy node in the cluster has recently
	// heartbeated to the Management API (the embedded client is connected).
	Online *bool `json:"online,omitempty"`
	// ConnectedProxies is the number of proxy nodes currently connected to the
	// cluster (per the Management API).
	ConnectedProxies *int `json:"connectedProxies,omitempty"`
}

// ReverseProxyClusterStatusApplyConfiguration constructs a declarative configuration of the ReverseProxyClusterStatus type for use with
// apply.
func ReverseProxyClusterStatus() *ReverseProxyClusterStatusApplyConfiguration {
	return &ReverseProxyClusterStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithObservedGeneration(value int64) *ReverseProxyClusterStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ReverseProxyClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithClusterAddress sets the ClusterAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterAddress field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithClusterAddress(value string) *ReverseProxyClusterStatusApplyConfiguration {
	b.ClusterAddress = &value
	return b
}

// WithTokenID sets the TokenID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenID field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithTokenID(value string) *ReverseProxyClusterStatusApplyConfiguration {
	b.TokenID = &value
	return b
}

// WithDomainID sets the DomainID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainID field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithDomainID(value string) *ReverseProxyClusterStatusApplyConfiguration {
	b.DomainID = &value
	return b
}

// WithLoadBalancerIP sets the LoadBalancerIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancerIP field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithLoadBalancerIP(value string) *ReverseProxyClusterStatusApplyConfiguration {
	b.LoadBalancerIP = &value
	return b
}

// WithOnline sets the Online field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Online field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithOnline(value bool) *ReverseProxyClusterStatusApplyConfiguration {
	b.Online = &value
	return b
}

// WithConnectedProxies sets the ConnectedProxies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectedProxies field is set to the value of the last call.
func (b *ReverseProxyClusterStatusApplyConfiguration) WithConnectedProxies(value int) *ReverseProxyClusterStatusApplyConfiguration {
	b.ConnectedProxies = &value
	return b
}
