// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ReverseProxyClusterSpecApplyConfiguration represents a declarative configuration of the ReverseProxyClusterSpec type for use
// with apply.
//
// ReverseProxyClusterSpec defines the desired state of ReverseProxyCluster. It
// is admin-authored: creating one deploys and enrolls a NetBird bring-your-own
// reverse proxy (the netbirdio/reverse-proxy image) and registers it as the
// account's own proxy cluster. The proxy runs behind a Service type=LoadBalancer
// (its ingress IP comes from the cluster's LB-IPAM) and is reached over the
// mesh; ReverseProxyService.proxyCluster targets its ClusterAddress.
type ReverseProxyClusterSpecApplyConfiguration struct {
	// ClusterAddress is the address the proxy registers under (the proxy's
	// NB_PROXY_DOMAIN), e.g. "gate.ccbash.cloud". ReverseProxyService.proxyCluster
	// references it. It must sit under Domain so service domains derive this
	// cluster.
	ClusterAddress *string `json:"clusterAddress,omitempty"`
	// Domain is the DNS zone the proxy fronts, e.g. "ccbash.cloud". The operator
	// ensures a DNSZone for it (unless ZoneRef is set) and creates the proxy's A
	// record (ClusterAddress -> the LoadBalancer IP) plus a catch-all
	// (*.Domain -> ClusterAddress) so any service hostname resolves to the proxy.
	Domain *string `json:"domain,omitempty"`
	// ZoneRef references an existing DNSZone for Domain instead of creating one.
	ZoneRef *CrossNamespaceReferenceApplyConfiguration `json:"zoneRef,omitempty"`
	// CertSecretName is a kubernetes.io/tls Secret (tls.crt/tls.key) in the same
	// namespace — typically a cert-manager wildcard for Domain — mounted into the
	// proxy as its static TLS certificate. The proxy does no ACME.
	CertSecretName *string `json:"certSecretName,omitempty"`
	// Groups are NetBird groups the proxy's advertised LoadBalancer resource
	// joins, so access policies can target it.
	Groups []GroupReferenceApplyConfiguration `json:"groups,omitempty"`
	// Private enables NetBird-Only access for services on this cluster. The proxy
	// then runs an embedded netbird client (a mesh peer, userspace WireGuard — no
	// extra privileges), which the cluster needs to serve private (mesh-only)
	// services. Group-based services keep working regardless.
	Private *bool `json:"private,omitempty"`
	// Replicas of the proxy Deployment. Defaults to 1.
	Replicas *int32 `json:"replicas,omitempty"`
	// Image overrides the netbird reverse-proxy image. Defaults to the operator's
	// pinned image.
	Image *string `json:"image,omitempty"`
	// ServiceAnnotations are added to the proxy's LoadBalancer Service, e.g. to
	// pin an LB-IPAM pool or request a specific IP.
	ServiceAnnotations map[string]string `json:"serviceAnnotations,omitempty"`
}

// ReverseProxyClusterSpecApplyConfiguration constructs a declarative configuration of the ReverseProxyClusterSpec type for use with
// apply.
func ReverseProxyClusterSpec() *ReverseProxyClusterSpecApplyConfiguration {
	return &ReverseProxyClusterSpecApplyConfiguration{}
}

// WithClusterAddress sets the ClusterAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterAddress field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithClusterAddress(value string) *ReverseProxyClusterSpecApplyConfiguration {
	b.ClusterAddress = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithDomain(value string) *ReverseProxyClusterSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithZoneRef sets the ZoneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneRef field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithZoneRef(value *CrossNamespaceReferenceApplyConfiguration) *ReverseProxyClusterSpecApplyConfiguration {
	b.ZoneRef = value
	return b
}

// WithCertSecretName sets the CertSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertSecretName field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithCertSecretName(value string) *ReverseProxyClusterSpecApplyConfiguration {
	b.CertSecretName = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithGroups(values ...*GroupReferenceApplyConfiguration) *ReverseProxyClusterSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGroups")
		}
		b.Groups = append(b.Groups, *values[i])
	}
	return b
}

// WithPrivate sets the Private field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Private field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithPrivate(value bool) *ReverseProxyClusterSpecApplyConfiguration {
	b.Private = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithReplicas(value int32) *ReverseProxyClusterSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithImage(value string) *ReverseProxyClusterSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithServiceAnnotations puts the entries into the ServiceAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ServiceAnnotations field,
// overwriting an existing map entries in ServiceAnnotations field with the same key.
func (b *ReverseProxyClusterSpecApplyConfiguration) WithServiceAnnotations(entries map[string]string) *ReverseProxyClusterSpecApplyConfiguration {
	if b.ServiceAnnotations == nil && len(entries) > 0 {
		b.ServiceAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ServiceAnnotations[k] = v
	}
	return b
}
