// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/netbirdio/kubernetes-operator/api/v1alpha1"
)

// ReverseProxyServiceSpecApplyConfiguration represents a declarative configuration of the ReverseProxyServiceSpec type for use
// with apply.
//
// ReverseProxyServiceSpec defines the desired state of ReverseProxyService. It
// is admin-authored — creating one is the explicit decision to expose Services
// through the NetBird reverse proxy, internally or externally. It mirrors the
// NetBird reverse-proxy service API (POST /api/reverse-proxies/services),
// targeting the DNSRecord FQDN that belongs to each backend LoadBalancer Service.
type ReverseProxyServiceSpecApplyConfiguration struct {
	// Backends are the LoadBalancer Services this service proxies to, by path.
	Backends []ReverseProxyBackendApplyConfiguration `json:"backends,omitempty"`
	// Mode selects the proxy mode. "http" (default) is an L7 reverse proxy;
	// "tcp"/"tls"/"udp" are L4 passthrough on ListenPort. Expose several L4 ports
	// under one hostname with one CR per port (same Domain, distinct ListenPort).
	Mode *apiv1alpha1.ReverseProxyMode `json:"mode,omitempty"`
	// ListenPort is the port the proxy listens on (L4 modes only — tcp/tls/udp).
	// 0 (or unset) lets NetBird auto-assign. Ignored for mode=http.
	ListenPort *int `json:"listenPort,omitempty"`
	// ProxyProtocol, when true, makes the proxy prepend a PROXY protocol v2
	// header to each backend connection so the backend sees the real client IP
	// and port instead of the proxy's. Applies to tcp/tls modes only (the
	// NetBird API rejects it elsewhere; HTTP conveys the client IP via
	// X-Forwarded-For). Required for mail backends that enforce SPF/DNSBL,
	// greylist, or log the client address — the backend must be configured to
	// accept PROXY protocol on the listening port.
	ProxyProtocol *bool `json:"proxyProtocol,omitempty"`
	// ProxyCluster is the address of the NetBird reverse-proxy cluster that
	// serves this service, e.g. "gate.example.com". The operator resolves it to
	// a proxy-cluster ID and points the service's targets at it.
	ProxyCluster *string `json:"proxyCluster,omitempty"`
	// Domain is the hostname the service is published under.
	Domain *string `json:"domain,omitempty"`
	// Private, when true, makes the service NetBird-only: inbound peers
	// authenticate via their tunnel identity (no OIDC) and an ACL policy is
	// auto-generated from AccessGroups.
	Private *bool `json:"private,omitempty"`
	// AccessGroups are the NetBird groups whose peers may reach a private
	// service over the tunnel. Required when Private is true; ignored otherwise.
	AccessGroups []GroupReferenceApplyConfiguration `json:"accessGroups,omitempty"`
	// CrowdsecMode sets the CrowdSec IP-reputation handling for the service.
	CrowdsecMode *apiv1alpha1.CrowdsecMode `json:"crowdsecMode,omitempty"`
	// AccessRestrictions sets IP/geo connection-level restrictions.
	AccessRestrictions *AccessRestrictionsApplyConfiguration `json:"accessRestrictions,omitempty"`
	// PassHostHeader, when true, forwards the original client Host header to the
	// backend instead of rewriting it to the backend address.
	PassHostHeader *bool `json:"passHostHeader,omitempty"`
	// RewriteRedirects, when true, rewrites Location headers in backend
	// responses to replace the backend address with the public domain.
	RewriteRedirects *bool `json:"rewriteRedirects,omitempty"`
}

// ReverseProxyServiceSpecApplyConfiguration constructs a declarative configuration of the ReverseProxyServiceSpec type for use with
// apply.
func ReverseProxyServiceSpec() *ReverseProxyServiceSpecApplyConfiguration {
	return &ReverseProxyServiceSpecApplyConfiguration{}
}

// WithBackends adds the given value to the Backends field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Backends field.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithBackends(values ...*ReverseProxyBackendApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBackends")
		}
		b.Backends = append(b.Backends, *values[i])
	}
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithMode(value apiv1alpha1.ReverseProxyMode) *ReverseProxyServiceSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithListenPort sets the ListenPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ListenPort field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithListenPort(value int) *ReverseProxyServiceSpecApplyConfiguration {
	b.ListenPort = &value
	return b
}

// WithProxyProtocol sets the ProxyProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyProtocol field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithProxyProtocol(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.ProxyProtocol = &value
	return b
}

// WithProxyCluster sets the ProxyCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyCluster field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithProxyCluster(value string) *ReverseProxyServiceSpecApplyConfiguration {
	b.ProxyCluster = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithDomain(value string) *ReverseProxyServiceSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithPrivate sets the Private field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Private field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithPrivate(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.Private = &value
	return b
}

// WithAccessGroups adds the given value to the AccessGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessGroups field.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithAccessGroups(values ...*GroupReferenceApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccessGroups")
		}
		b.AccessGroups = append(b.AccessGroups, *values[i])
	}
	return b
}

// WithCrowdsecMode sets the CrowdsecMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CrowdsecMode field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithCrowdsecMode(value apiv1alpha1.CrowdsecMode) *ReverseProxyServiceSpecApplyConfiguration {
	b.CrowdsecMode = &value
	return b
}

// WithAccessRestrictions sets the AccessRestrictions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessRestrictions field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithAccessRestrictions(value *AccessRestrictionsApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	b.AccessRestrictions = value
	return b
}

// WithPassHostHeader sets the PassHostHeader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PassHostHeader field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithPassHostHeader(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.PassHostHeader = &value
	return b
}

// WithRewriteRedirects sets the RewriteRedirects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RewriteRedirects field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithRewriteRedirects(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.RewriteRedirects = &value
	return b
}
