// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ReverseProxyClusterParametersSpecApplyConfiguration represents a declarative configuration of the ReverseProxyClusterParametersSpec type for use
// with apply.
//
// ReverseProxyClusterParametersSpec is the GatewayClass-level "flavor" shared by
// every Gateway of that class: the parts of a ReverseProxyCluster that aren't
// derived from a Gateway's own listeners. A Gateway derives its domain,
// clusterAddress and cert from its listeners; these fill in the rest.
type ReverseProxyClusterParametersSpecApplyConfiguration struct {
	// Image overrides the netbird reverse-proxy image. Defaults to the operator's
	// pinned image.
	Image *string `json:"image,omitempty"`
	// Replicas of the proxy Deployment. Defaults to 1.
	Replicas *int32 `json:"replicas,omitempty"`
	// Groups are NetBird groups the proxy's advertised LoadBalancer resource
	// joins, so access policies can target it.
	Groups []GroupReferenceApplyConfiguration `json:"groups,omitempty"`
	// Private enables NetBird-Only services: the proxy runs an embedded netbird
	// client (userspace WireGuard). Group-based services work regardless.
	Private *bool `json:"private,omitempty"`
	// ServiceAnnotations are added to each Gateway's proxy LoadBalancer Service,
	// e.g. to pin an LB-IPAM pool.
	ServiceAnnotations map[string]string `json:"serviceAnnotations,omitempty"`
}

// ReverseProxyClusterParametersSpecApplyConfiguration constructs a declarative configuration of the ReverseProxyClusterParametersSpec type for use with
// apply.
func ReverseProxyClusterParametersSpec() *ReverseProxyClusterParametersSpecApplyConfiguration {
	return &ReverseProxyClusterParametersSpecApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ReverseProxyClusterParametersSpecApplyConfiguration) WithImage(value string) *ReverseProxyClusterParametersSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ReverseProxyClusterParametersSpecApplyConfiguration) WithReplicas(value int32) *ReverseProxyClusterParametersSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *ReverseProxyClusterParametersSpecApplyConfiguration) WithGroups(values ...*GroupReferenceApplyConfiguration) *ReverseProxyClusterParametersSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGroups")
		}
		b.Groups = append(b.Groups, *values[i])
	}
	return b
}

// WithPrivate sets the Private field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Private field is set to the value of the last call.
func (b *ReverseProxyClusterParametersSpecApplyConfiguration) WithPrivate(value bool) *ReverseProxyClusterParametersSpecApplyConfiguration {
	b.Private = &value
	return b
}

// WithServiceAnnotations puts the entries into the ServiceAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ServiceAnnotations field,
// overwriting an existing map entries in ServiceAnnotations field with the same key.
func (b *ReverseProxyClusterParametersSpecApplyConfiguration) WithServiceAnnotations(entries map[string]string) *ReverseProxyClusterParametersSpecApplyConfiguration {
	if b.ServiceAnnotations == nil && len(entries) > 0 {
		b.ServiceAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ServiceAnnotations[k] = v
	}
	return b
}
