// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ReverseProxyBackendApplyConfiguration represents a declarative configuration of the ReverseProxyBackend type for use
// with apply.
//
// ReverseProxyBackend names a Service this service proxies to. How the proxy
// reaches it depends on the Service type: a type=LoadBalancer Service must be
// advertised (have a DNSRecord) and is targeted by its dualstack mesh FQDN (so
// IPv4/IPv6 is transparent, over the NetBird overlay); any other Service
// (ClusterIP) is reached directly at its in-cluster DNS name — the drop-in path
// for an in-cluster proxy.
type ReverseProxyBackendApplyConfiguration struct {
	// ServiceRef names the Service to proxy to, in the same namespace as the
	// ReverseProxyService.
	ServiceRef *v1.LocalObjectReference `json:"serviceRef,omitempty"`
	// Port the proxy dials on the backend. Defaults to the Service's first port.
	Port *int `json:"port,omitempty"`
	// Path is the URL path prefix this backend serves (HTTP). Defaults to "/".
	Path *string `json:"path,omitempty"`
}

// ReverseProxyBackendApplyConfiguration constructs a declarative configuration of the ReverseProxyBackend type for use with
// apply.
func ReverseProxyBackend() *ReverseProxyBackendApplyConfiguration {
	return &ReverseProxyBackendApplyConfiguration{}
}

// WithServiceRef sets the ServiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceRef field is set to the value of the last call.
func (b *ReverseProxyBackendApplyConfiguration) WithServiceRef(value v1.LocalObjectReference) *ReverseProxyBackendApplyConfiguration {
	b.ServiceRef = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ReverseProxyBackendApplyConfiguration) WithPort(value int) *ReverseProxyBackendApplyConfiguration {
	b.Port = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ReverseProxyBackendApplyConfiguration) WithPath(value string) *ReverseProxyBackendApplyConfiguration {
	b.Path = &value
	return b
}
