// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/netbirdio/kubernetes-operator/api/v1alpha1"
)

// ReverseProxyServiceSpecApplyConfiguration represents a declarative configuration of the ReverseProxyServiceSpec type for use
// with apply.
//
// ReverseProxyServiceSpec defines the desired state of ReverseProxyService. It
// is admin-authored — creating one is the explicit decision to expose a route
// through the NetBird reverse proxy. It mirrors the NetBird reverse-proxy
// service API (POST /api/reverse-proxies/services), but derives its targets
// from the referenced route's backends rather than listing them by hand.
type ReverseProxyServiceSpecApplyConfiguration struct {
	// RouteRef identifies the HTTPRoute or TCPRoute whose backends this service
	// exposes.
	RouteRef *RouteReferenceApplyConfiguration `json:"routeRef,omitempty"`
	// ProxyCluster is the address of the NetBird reverse-proxy cluster that
	// serves this service, e.g. "gate.example.com". The operator resolves it to
	// a proxy-cluster ID and points the service's targets at it.
	ProxyCluster *string `json:"proxyCluster,omitempty"`
	// Domain is the public hostname the service is published under. Defaults to
	// the referenced route's hostname when empty.
	Domain *string `json:"domain,omitempty"`
	// Upstream selects how the proxy reaches the backend: "hostname" (default)
	// targets the Service FQDN so the proxy resolves it via NetBird DNS
	// (IPv4/IPv6 transparent); "ip" targets the ClusterIP directly.
	Upstream *apiv1alpha1.UpstreamMode `json:"upstream,omitempty"`
	// Private, when true, makes the service NetBird-only: inbound peers
	// authenticate via their tunnel identity (no OIDC) and an ACL policy is
	// auto-generated from AccessGroups.
	Private *bool `json:"private,omitempty"`
	// AccessGroups are the NetBird groups whose peers may reach a private
	// service over the tunnel. Required when Private is true; ignored otherwise.
	AccessGroups []GroupReferenceApplyConfiguration `json:"accessGroups,omitempty"`
	// CrowdsecMode sets the CrowdSec IP-reputation handling for the service.
	CrowdsecMode *apiv1alpha1.CrowdsecMode `json:"crowdsecMode,omitempty"`
	// AccessRestrictions sets IP/geo connection-level restrictions.
	AccessRestrictions *AccessRestrictionsApplyConfiguration `json:"accessRestrictions,omitempty"`
	// PassHostHeader, when true, forwards the original client Host header to the
	// backend instead of rewriting it to the backend address.
	PassHostHeader *bool `json:"passHostHeader,omitempty"`
	// RewriteRedirects, when true, rewrites Location headers in backend
	// responses to replace the backend address with the public domain.
	RewriteRedirects *bool `json:"rewriteRedirects,omitempty"`
}

// ReverseProxyServiceSpecApplyConfiguration constructs a declarative configuration of the ReverseProxyServiceSpec type for use with
// apply.
func ReverseProxyServiceSpec() *ReverseProxyServiceSpecApplyConfiguration {
	return &ReverseProxyServiceSpecApplyConfiguration{}
}

// WithRouteRef sets the RouteRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouteRef field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithRouteRef(value *RouteReferenceApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	b.RouteRef = value
	return b
}

// WithProxyCluster sets the ProxyCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyCluster field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithProxyCluster(value string) *ReverseProxyServiceSpecApplyConfiguration {
	b.ProxyCluster = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithDomain(value string) *ReverseProxyServiceSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithUpstream sets the Upstream field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Upstream field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithUpstream(value apiv1alpha1.UpstreamMode) *ReverseProxyServiceSpecApplyConfiguration {
	b.Upstream = &value
	return b
}

// WithPrivate sets the Private field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Private field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithPrivate(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.Private = &value
	return b
}

// WithAccessGroups adds the given value to the AccessGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AccessGroups field.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithAccessGroups(values ...*GroupReferenceApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccessGroups")
		}
		b.AccessGroups = append(b.AccessGroups, *values[i])
	}
	return b
}

// WithCrowdsecMode sets the CrowdsecMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CrowdsecMode field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithCrowdsecMode(value apiv1alpha1.CrowdsecMode) *ReverseProxyServiceSpecApplyConfiguration {
	b.CrowdsecMode = &value
	return b
}

// WithAccessRestrictions sets the AccessRestrictions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessRestrictions field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithAccessRestrictions(value *AccessRestrictionsApplyConfiguration) *ReverseProxyServiceSpecApplyConfiguration {
	b.AccessRestrictions = value
	return b
}

// WithPassHostHeader sets the PassHostHeader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PassHostHeader field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithPassHostHeader(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.PassHostHeader = &value
	return b
}

// WithRewriteRedirects sets the RewriteRedirects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RewriteRedirects field is set to the value of the last call.
func (b *ReverseProxyServiceSpecApplyConfiguration) WithRewriteRedirects(value bool) *ReverseProxyServiceSpecApplyConfiguration {
	b.RewriteRedirects = &value
	return b
}
