// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RouteReferenceApplyConfiguration represents a declarative configuration of the RouteReference type for use
// with apply.
//
// RouteReference identifies the Gateway-API route whose backends a
// ReverseProxyService exposes. The route must be in the same namespace.
type RouteReferenceApplyConfiguration struct {
	// Group is the route's API group.
	Group *string `json:"group,omitempty"`
	// Kind is the route kind.
	Kind *string `json:"kind,omitempty"`
	// Name of the route.
	Name *string `json:"name,omitempty"`
}

// RouteReferenceApplyConfiguration constructs a declarative configuration of the RouteReference type for use with
// apply.
func RouteReference() *RouteReferenceApplyConfiguration {
	return &RouteReferenceApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *RouteReferenceApplyConfiguration) WithGroup(value string) *RouteReferenceApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *RouteReferenceApplyConfiguration) WithKind(value string) *RouteReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RouteReferenceApplyConfiguration) WithName(value string) *RouteReferenceApplyConfiguration {
	b.Name = &value
	return b
}
