// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RouterDeployApplyConfiguration represents a declarative configuration of the RouterDeploy type for use
// with apply.
//
// RouterDeploy configures the netbird-client DaemonSet for peers.deploy.
type RouterDeployApplyConfiguration struct {
	// NodeSelector limits the DaemonSet to matching nodes (default: all nodes).
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// Image overrides the netbird-client image (default: the operator's
	// configured client image).
	Image *string `json:"image,omitempty"`
	// LogLevel for the netbird client.
	LogLevel *string `json:"logLevel,omitempty"`
}

// RouterDeployApplyConfiguration constructs a declarative configuration of the RouterDeploy type for use with
// apply.
func RouterDeploy() *RouterDeployApplyConfiguration {
	return &RouterDeployApplyConfiguration{}
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *RouterDeployApplyConfiguration) WithNodeSelector(entries map[string]string) *RouterDeployApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *RouterDeployApplyConfiguration) WithImage(value string) *RouterDeployApplyConfiguration {
	b.Image = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *RouterDeployApplyConfiguration) WithLogLevel(value string) *RouterDeployApplyConfiguration {
	b.LogLevel = &value
	return b
}
