// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServiceCIDRResourceApplyConfiguration represents a declarative configuration of the ServiceCIDRResource type for use
// with apply.
//
// ServiceCIDRResource tracks the NetBird subnet resource created for a CIDR.
type ServiceCIDRResourceApplyConfiguration struct {
	// CIDR is the routed range.
	CIDR *string `json:"cidr,omitempty"`
	// ResourceID is the NetBird network resource id.
	ResourceID *string `json:"resourceID,omitempty"`
}

// ServiceCIDRResourceApplyConfiguration constructs a declarative configuration of the ServiceCIDRResource type for use with
// apply.
func ServiceCIDRResource() *ServiceCIDRResourceApplyConfiguration {
	return &ServiceCIDRResourceApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *ServiceCIDRResourceApplyConfiguration) WithCIDR(value string) *ServiceCIDRResourceApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithResourceID sets the ResourceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceID field is set to the value of the last call.
func (b *ServiceCIDRResourceApplyConfiguration) WithResourceID(value string) *ServiceCIDRResourceApplyConfiguration {
	b.ResourceID = &value
	return b
}
